# Generated by Django 4.2.4 on 2023-09-11 16:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("phones", "0002_alter_phone_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="phone",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="phone",
            name="image",
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name="phone",
            name="name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="phone",
            name="price",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="phone",
            name="release_date",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="phone",
            name="slug",
            field=models.SlugField(unique=True),
        ),
    ]
