# Generated by Django 4.2.4 on 2023-09-11 17:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("phones", "0003_alter_phone_id_alter_phone_image_alter_phone_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="phone",
            name="id",
            field=models.PositiveIntegerField(
                primary_key=True, serialize=False, verbose_name="id"
            ),
        ),
        migrations.AlterField(
            model_name="phone",
            name="image",
            field=models.URLField(verbose_name="image"),
        ),
        migrations.AlterField(
            model_name="phone",
            name="name",
            field=models.CharField(max_length=100, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="phone",
            name="price",
            field=models.PositiveIntegerField(verbose_name="price"),
        ),
        migrations.AlterField(
            model_name="phone",
            name="release_date",
            field=models.DateField(verbose_name="release_date"),
        ),
        migrations.AlterField(
            model_name="phone",
            name="slug",
            field=models.SlugField(max_length=150, unique=True),
        ),
    ]
