# Generated by Django 4.2.4 on 2023-09-11 19:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("phones", "0004_alter_phone_id_alter_phone_image_alter_phone_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="phone",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="phone",
            name="image",
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name="phone",
            name="name",
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name="phone",
            name="price",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="phone",
            name="release_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="phone",
            name="slug",
            field=models.SlugField(max_length=60),
        ),
    ]
